version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-truffle:
          pkg-manager: npm install -g truffle
      - node/install-packages:
          pkg-manager: npm install
      - run:
          command: truffle compile
          name: Build the project
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-truffle:
          pkg-manager: npm install -g truffle
      - node/install-packages:
          pkg-manager: npm install
      - run:
          command: truffle test
          name: Test the project

workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
