# name: Tests

# on:
#   push:
#     branches:
#       - master
#       - develop

#   pull_request:
#     branches:
#       - "*"

# jobs:
#   compile:
#     runs-on: self-hosted
#     continue-on-error: false
#     steps:
#       - uses: actions/checkout@v3
#       - run: npm install -g truffle
#       - run: npm install
#       - run: truffle compile
#   tests:
#     needs: compile
#     runs-on: self-hosted
#     continue-on-error: false
#     steps:
#       - uses: actions/checkout@v3
#       - run: npm install -g truffle
#       - run: npm install
#       - run: truffle test